### ISSUE TITLE
Global proxy suffers from 'illegal argument String.blit' while uploading

### ISSUE THREAD

**Issue by toolslive** [openvstorage/alba#825] opened 2017-10-19 13:04 UTC
It causes either to the `AlbaOsd` to be disqualified (see #797 ) or (when the Fail fast workaround is in place, the proxy to shut die)
```
alba/proxy - 2264 - fatal - Fail fast:"Raised by primitive operation at file \"src/tools/lwt_bytes2.ml.cppo\", line 44, characters 14-39
Called from file \"src/tools/object_reader.ml\", line 93, characters 4-49
Called from file \"src/tools/prelude.ml\", line 971, characters 2-6
Called from file \"src/alba_client_upload.ml\", line 493, characters 6-104
Called from file \"src/alba_client_upload.ml\", line 667, characters 4-46
Called from file \"src/core/lwt.ml\", line 785, characters 20-24
Called from file \"src/alba_client_upload.ml\", line 670, characters 2-159
Called from file \"src/alba_client_sequence.ml\", line 30, characters 4-578
Called from file \"src/list.ml\", line 325, characters 13-17
Called from file \"src/list.ml\" (inlined), line 346, characters 15-31
Called from file \"src/tools/prelude.ml\" (inlined), line 140, characters 16-34
Called from file \"src/tools/prelude.ml\" (inlined), line 933, characters 13-25
Called from file \"src/alba_client_sequence.ml\", line 57, characters 2-285
Called from file \"src/core/lwt.ml\", line 715, characters 66-71
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 202, characters 8-15
Called from file \"src/core/lwt.ml\", line 306, characters 2-34
Called from file \"src/unix/lwt_unix.cppo.ml\", line 218, characters 31-51
...
```

**Comment by wimpers** [comment] 2017-12-14 10:34
@domsj can you pick this one up in the context of  trying to fix the fail fast issues.

**Comment by domsj** [comment] 2017-12-14 12:02
Great, just the ticket I needed, I'm hoping it would be fixed (for real this time) in https://github.com/openvstorage/alba_ee/pull/167.
Will be available as of alba 1.5.20 / 1.6.2.

**Comment by wimpers** [comment] 2018-03-06 10:56
@domsj what is the status of this ticket? Can this be closed

**Comment by domsj** [comment] 2018-03-07 14:04
This is not yet fully fixed.
@andersfugmann made it reproducible in https://github.com/openvstorage/alba_ee/pull/256
after which I analysed the (debug) logs and made the following change, which should make it occur less, but it's not a proper fix: https://github.com/openvstorage/alba_ee/pull/250.
So some work remains to be done, and this issue should not yet be closed.

**Comment by domsj** [comment] 2018-03-07 16:02
actually this could be closed as a duplicate of https://github.com/openvstorage/alba_ee/issues/187 (or the other way around)

**Closed** 2018-03-27 08:30 UTC
Labels: process_duplicate, type_bug
