### ISSUE TITLE
[ASD] error during client request: Prelude.DecodingFailure("bool: invalid tag 0x61")

### ISSUE THREAD

**Issue by kinvaris** [openvstorage/alba#323] opened 2016-08-11 12:01 UTC
While performing a fio test on a vpool we saw this error on a ASD:

This happened during this test: https://github.com/ovs-projects/org_quality/issues/22

Also the volumedriver and proxy communication between each other has been changed to `TCP` in addition to the above ticket.

```
2016-08-11 13:50:25 393301 +0200 - str02 - 19600/0 - alba/asd - 293 - info - server: new client connection from (172.19.12.141,41983)
2016-08-11 13:50:26 700716 +0200 - str02 - 19600/0 - alba/asd - 294 - info - reading from fd: 632120B in 11 steps
2016-08-11 13:50:37 665169 +0200 - str02 - 19600/0 - alba/asd - 295 - info - reading from fd: 994966B in 19 steps
2016-08-11 13:50:46 102283 +0200 - str02 - 19600/0 - alba/asd - 296 - info - maxrss:44920 KB, allocated:44227.726562, minor_collections:23, major_collections:2, c
ompactions:0, heap_words:491520
2016-08-11 13:50:46 102540 +0200 - str02 - 19600/0 - alba/asd - 297 - info - {;         creation: 2016/08/11_11:59:45.5895;;    period: 0.00;;   Statistics : { St
at.Stat.n = 26L; avg = 3.29567835881e-05; exp_avg = 3.01622883747e-05;;   m2 = 7.05007061277e-10; var = 2.82002824511e-11; min = 2.59876251221e-05;;   max = 4.816
05529785e-05; alpha = 0.9 };;       Range : { Stat.Stat.n = 8L; avg = 0.000156342983246; exp_avg = 9.02095691323e-05;;   m2 = 6.02412342232e-09; var = 8.605890603
32e-10; min = 0.000131845474243;;   max = 0.000211000442505; alpha = 0.9 };;      MultiGet2 : { Stat.Stat.n = 27L; avg = 0.181439823574; exp_avg = 0.179720160651;
;   m2 = 1.28912914898; var = 0.0495818903454; min = 7.5101852417e-05;;   max = 0.515853881836; alpha = 0.9 };;         Apply : { Stat.Stat.n = 41L; avg = 0.02284
1971095; exp_avg = 0.0594903363469;;   m2 = 0.339744026786; var = 0.00849360066964; min = 0.000402927398682;;   max = 0.485781908035; alpha = 0.9 };;         GetD
iskUsage : { Stat.Stat.n = 241L; avg = 2.39625511328e-05; exp_avg = 2.55106568546e-05;;   m2 = 1.36671042505e-08; var = 5.69462677106e-11; min = 1.09672546387e-05
;;   max = 7.10487365723e-05; alpha = 0.9 };;     Capabilities : { Stat.Stat.n = 215L; avg = 2.27717466133e-05; exp_avg = 1.98782618404e-05;;   m2 = 9.26478362597
e-07; var = 4.32933814298e-09; min = 1.09672546387e-05;;   max = 0.000981092453003; alpha = 0.9 };;     }
2016-08-11 13:50:55 99090 +0200 - str02 - 19600/0 - alba/asd - 298 - info - server: new client connection from (172.19.12.141,36427)
2016-08-11 13:50:55 124672 +0200 - str02 - 19600/0 - alba/asd - 299 - info - reading from fd: 524317B in 10 steps
2016-08-11 13:50:55 227253 +0200 - str02 - 19600/0 - alba/asd - 300 - info - server: new client connection from (172.19.12.141,53341)
2016-08-11 13:50:55 231251 +0200 - str02 - 19600/0 - alba/asd - 301 - info - server: new client connection from (172.19.12.141,50379)
2016-08-11 13:50:55 248783 +0200 - str02 - 19600/0 - alba/asd - 302 - info - reading from fd: 626562B in 9 steps
2016-08-11 13:50:57 163284 +0200 - str02 - 19600/0 - alba/asd - 303 - info - reading from fd: 873788B in 22 steps
2016-08-11 13:50:57 172183 +0200 - str02 - 19600/0 - alba/asd - 304 - info - server: new client connection from (172.19.12.141,40760)
2016-08-11 13:50:57 177460 +0200 - str02 - 19600/0 - alba/asd - 305 - info - reading from fd: 524317B in 12 steps
2016-08-11 13:51:12 407829 +0200 - str02 - 19600/0 - alba/asd - 306 - info - server: new client connection from (172.19.12.141,59907)
2016-08-11 13:51:12 418011 +0200 - str02 - 19600/0 - alba/asd - 307 - info - reading from fd: 524317B in 10 steps
2016-08-11 13:51:29 742925 +0200 - str02 - 19600/0 - alba/asd - 308 - info - reading from fd: 961892B in 13 steps
2016-08-11 13:51:29 743125 +0200 - str02 - 19600/0 - alba/asd - 309 - info - error during client request: Prelude.DecodingFailure("bool: invalid tag 0x61"): Prelu
de.DecodingFailure("bool: invalid tag 0x61"); backtrace:; Raised at file "map.ml", line 117, characters 16-25; Called from file "lib/conv.ml", line 213, character
s 10-37
2016-08-11 13:51:29 800545 +0200 - str02 - 19600/0 - alba/asd - 310 - info - server: new client connection from (172.19.12.141,43535)
2016-08-11 13:51:29 807454 +0200 - str02 - 19600/0 - alba/asd - 311 - info - server: new client connection from (172.19.12.141,57840)
2016-08-11 13:51:29 816725 +0200 - str02 - 19600/0 - alba/asd - 312 - info - server: new client connection from (172.19.12.141,36049)
2016-08-11 13:51:29 817703 +0200 - str02 - 19600/0 - alba/asd - 313 - info - reading from fd: 795581B in 15 steps
2016-08-11 13:51:29 829866 +0200 - str02 - 19600/0 - alba/asd - 314 - info - server: new client connection from (172.19.12.141,40300)
2016-08-11 13:51:46 109014 +0200 - str02 - 19600/0 - alba/asd - 315 - info - maxrss:45556 KB, allocated:46280.390625, minor_collections:24, major_collections:2, c
ompactions:0, heap_words:491520
2016-08-11 13:51:46 109317 +0200 - str02 - 19600/0 - alba/asd - 316 - info - {;         creation: 2016/08/11_11:59:45.5895;;    period: 0.00;;   Statistics : { St
at.Stat.n = 26L; avg = 3.29567835881e-05; exp_avg = 3.01622883747e-05;;   m2 = 7.05007061277e-10; var = 2.82002824511e-11; min = 2.59876251221e-05;;   max = 4.816
05529785e-05; alpha = 0.9 };;       Range : { Stat.Stat.n = 8L; avg = 0.000156342983246; exp_avg = 9.02095691323e-05;;   m2 = 6.02412342232e-09; var = 8.605890603
32e-10; min = 0.000131845474243;;   max = 0.000211000442505; alpha = 0.9 };;      MultiGet2 : { Stat.Stat.n = 27L; avg = 0.181439823574; exp_avg = 0.179720160651;
;   m2 = 1.28912914898; var = 0.0495818903454; min = 7.5101852417e-05;;   max = 0.515853881836; alpha = 0.9 };;         Apply : { Stat.Stat.n = 48L; avg = 0.02009
16876396; exp_avg = 0.0304088216659;;   m2 = 0.341921908771; var = 0.00727493422917; min = 0.000211000442505;;   max = 0.485781908035; alpha = 0.9 };;        GetD
iskUsage : { Stat.Stat.n = 243L; avg = 2.39340856733e-05; exp_avg = 2.454508652e-05;;   m2 = 1.36949232604e-08; var = 5.65905919849e-11; min = 1.09672546387e-05;;
   max = 7.10487365723e-05; alpha = 0.9 };;       Capabilities : { Stat.Stat.n = 217L; avg = 2.26959105461e-05; exp_avg = 1.88598950509e-05;;   m2 = 9.26612976341
e-07; var = 4.28987489047e-09; min = 1.09672546387e-05;;   max = 0.000981092453003; alpha = 0.9 };;     }
2016-08-11 13:51:47 35859 +0200 - str02 - 19600/0 - alba/asd - 317 - info - server: new client connection from (172.19.12.141,51713)
2016-08-11 13:51:47 129868 +0200 - str02 - 19600/0 - alba/asd - 318 - info - server: new client connection from (172.19.12.141,39204)
```

**Comment by domsj** [comment] 2016-08-19 13:20
@kinvaris saw this exactly once, so I'll lower the priority a bit

**Comment by wimpers** [comment] 2016-10-25 15:41
@kinvaris , @domsj  @cnanakos  @redlicha  @toolslive Does this cause a hang of the volume?

**Comment by domsj** [comment] 2016-10-25 15:53
I think it didn't cause a hang of the volume

**Comment by wimpers** [comment] 2016-10-26 07:16
Since it didn't hang the volume, removing SRP label.

**Comment by toolslive** [comment] 2017-02-06 09:11
@kinvaris, @wimpers I think we can close this one ?

**Comment by wimpers** [comment] 2017-02-06 09:14
Re-open if we can reproduce

**Closed by wimpers** 2017-02-06 09:14 UTC
Labels: priority_normal, process_cantreproduce, type_bug
