### ISSUE TITLE
Stackoverflow when fetching proxy-statistics with --to-json

### ISSUE THREAD

**Issue by domsj** [openvstorage/alba#728] opened 2017-05-31 10:13 UTC
Related to https://github.com/openvstorage/alba/issues/200.
A proxy on the env of @dejonghb was used to create & delete a very large amount of namespaces.
When requesting statistics from this proxy with --to-json the client process died with a stackoverflow.
(Retrieving the statistics without --to-json did not crash, so I think the problem is either in the json library we use, or due to logging a very large string).

Workaround: clear the statistics, use --forget namespaces, or restart the proxy

On the server side the statistics call took 2 to 6 seconds.

We may want to consider clearing the statistics when a namespace gets deleted.
OTOH even that is not enough if the namespace delete happens via another proxy.

Tested this with the latest version from master
root@ftcmp04:~# /tmp/alba version
1.3.15-34-g251edb6
git_revision: "heads/master-0-g251edb6"

**Comment by toolslive** [comment] 2017-12-04 10:52
The problem is the generation of the json (It boils down to the use of a `List.map` in yojson which can overflow)

**Comment by toolslive** [comment] 2018-10-23 08:52
fixed in alba-ee 1.6.3

**Closed by toolslive** 2018-10-23 08:52 UTC
Labels: state_inprogress, type_bug
