### ISSUE TITLE
More data on backend after repair

### ISSUE THREAD

**Issue by JeffreyDevloo** [openvstorage/alba#492] opened 2016-12-08 15:08 UTC
### Problem description
When the maintenance kicks in to repair the lost objects for the backend, the used space keeps increasing.

In my case I have a vdisk with 1.36GB of data.
I have purged asds one by one and waited on repair tasks to avoid data loss.
Ultimately my backend usage went up from 2.2GB to 6GB
![selection_093](https://cloud.githubusercontent.com/assets/17570109/21014903/08b22dee-bd60-11e6-87b0-e0a55fb34050.png)
Even later:
![selection_094](https://cloud.githubusercontent.com/assets/17570109/21014909/0e449940-bd60-11e6-9a76-0f0590a48237.png)

df -h reports the same usage as the backend page does: (some of them are removed)
```
/dev/sde1                             9.8G  256M  9.6G   3% /mnt/alba-asd/i9qmICfJjwT3eXex
/dev/sdb1                             4.9G  2.2G  2.7G  45% /mnt/alba-asd/vtDR2lPxb7akhtAO
/dev/sdc1                             4.9G  2.5G  2.5G  50% /mnt/alba-asd/hN7stx4f57iF56hr
/dev/sdf1                             9.8G  256M  9.6G   3% /mnt/alba-asd/2mttm0RbuoVkQcLA
/dev/sda1                             4.9G  2.3G  2.6G  48% /mnt/alba-asd/P6R5oAXDn8nxJ7mE
/dev/sdg1                             9.8G  923M  8.9G  10% /mnt/alba-asd/E0SER88xb6P6laz3
```
But the namespace does not report that this much data has been stored on the namespace:
```
{
        "name": "c0692edd-d9ec-42fe-af2d-5fcd81d88a4c",
        "statistics": {
          "logical": 1467184084,
          "storage": 2301025597,
          "storage_per_osd": [
            [ 3, 310361215 ],
            [ 8, 429107239 ],
            [ 14, 329600168 ],
            [ 15, 505846032 ],
            [ 16, 194597345 ],
            [ 17, 531513598 ]
          ],
          "bucket_count": [ [ [ 2, 2, 4, 4 ], 378 ] ]
        },
        "namespace": {
          "id": 35,
          "name": "c0692edd-d9ec-42fe-af2d-5fcd81d88a4c",
          "nsm_host_id": "mybackend01-nsm_0",
          "state": "active",
          "preset_name": "default"
        }
      }

```

**Comment by domsj** [comment] 2016-12-08 15:34
Do you see this too when auto repair is disabled?

**Comment by JeffreyDevloo** [comment] 2016-12-09 08:46
When the autorepair was disabled I did not have this issue.

**Comment by domsj** [comment] 2016-12-09 08:52
In that case closing it as duplicate of https://github.com/openvstorage/alba/issues/312

**Closed by domsj** 2016-12-09 08:52 UTC
