### ISSUE TITLE
Provide osd-multistatistics

### ISSUE THREAD

**Issue by khenderick** [openvstorage/alba#749] opened 2017-07-05 09:59 UTC
Like `asd-multistatistics`, we'd like to have a more generic `osd-multistatistics` that does the same, but can also collect information from other types of OSDs (ASD, Active Drive, but not another backend).

**Comment by wimpers** [comment] 2017-09-26 15:58
@toolslive @domsj  isn't this a duplicate of https://github.com/openvstorage/alba/issues/745

**Comment by wimpers** [comment] 2017-11-13 13:20
After discussion with @toolslive closed as duplicate

**Closed by wimpers** 2017-11-13 13:20 UTC
Labels: type_feature
